apiVersion: v1
kind: Service
metadata:
  name: ilb-service
#   annotations:
#     cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP